
server:
  port: 8151
eureka:
  server:

    enable-self-preservation: false
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://172.16.0.128:8761/eureka
spring:
  application:
    name: housing2
    #新加的验证
  datasource:
    url: jdbc:mysql://172.16.0.234:3306/crebas?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: wssn#2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
  freemarker:
    charset: UTF-8
  redis:
    host: 172.16.0.128
    port: 6379
    password:
    lettuce:
      shutdown-timeout: 0
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 9
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
  #直接logging
  #     level:debug是不行的报错

  #开启下方代码才能输出logger.debug里面的东西
#logging:
#  level:
#    root: debug
logging:
  config: classpath:logback-spring.xml
