server:
  port: 8101
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://172.16.0.128:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #开启熔断器
feign:
  hystrix:
    enabled: true