eureka:
  client:
    service-url:
      defaultZone: http://172.16.0.128:8761/eureka
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8763
spring:
  application:
    name: hello2
    #zipkin监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

      #手动刷新用的本地配置无效
#management:
      ##  security:
    ###关闭安全验证，否则访问refresh端点时会提示权限不足
    ##    enabled: false
