server:
  port: 8150
spring:
#  mail:
#    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1
        min-idle: 0
  datasource:
    url: jdbc:mysql://172.16.0.234:3306/crebas?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: wssn#2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: housing
logging:
  config: classpath:logback-spring.xml
eureka:
  server:
    enable-self-preservation: false
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://172.16.0.128:8761/eureka/