
server:
  port: 8151
eureka:
  server:

    enable-self-preservation: false
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://172.16.0.128:8761/eureka
spring:
  application:
    name: hello3
    #新加的验证
  datasource:
    url: jdbc:mysql://172.16.0.234:3306/crebas?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: wssn#2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  freemarker:
    charset: UTF-8
mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
  #直接logging
  #     level:debug是不行的报错

  #开启下方代码才能输出logger.debug里面的东西
logging:
  level:
    root: debug