
server:
  port: 8152
eureka:
  server:

    enable-self-preservation: false
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://172.16.0.128:8761/eureka
#  instance:
#    prefer-ip-address: true
#    hostname: ${spring.cloud.client.ipAddress}
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: thireparty