server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    #设置为本地启动的方式
    active: native
  cloud:
    config:
      server:
        native:
          #配置文件所在目录，classpath（类路径）和（系统文件路径） file两种
          search-locations: classpath:properties/
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://172.16.0.128:8761/eureka